### ISSUE TITLE
Add GitHub actions to iiit-gpa

### ISSUE THREAD

**Issue by abhisheknaiidu** [abhisheknaiidu/iiitdmj-gpa#6]
Addition of GitHub actions will help to enhance the code quality and workflow or repository.
try to add `ESLint` and `prettier` Actions.

**Comment by BetaHuhn** [comment]
Hey, I'd like to work on this issue, can you assign me?

**Comment by abhisheknaiidu** [comment]
> Hey, I'd like to work on this issue, can you assign me?

Go Ahead! If you need any help, take a look at this :) 
https://github.com/abhisheknaiidu/a-pop

**Comment by BetaHuhn** [comment]
Could you also please add the "hacktoberfest" topic to the repository? Else this repository is regarded as not participating in Hacktoberfest.

**Comment by BetaHuhn** [comment]
Should I also create build and test actions which run the build, test:unit and test:e2e commands specified in the package.json?

**Comment by abhisheknaiidu** [comment]
> Could you also please add the "hacktoberfest" topic to the repository? Else this repository is regarded as not participating in Hacktoberfest.

Yup, I've done now, thanks for informing me!
