### ISSUE TITLE
Provide a Good Documentation

### ISSUE THREAD

**Issue by abhisheknaiidu** [abhisheknaiidu/iiitdmj-gpa#9]
##  Documentation
Provide a good documentation, so that it can attract and users can read properly

**Comment by Priyanshu-official** [comment]
@abhisheknaiidu I would Like to Work can you Assign to me

**Comment by abhisheknaiidu** [comment]
@Priyanshu-official Go Ahead, try to make like this https://github.com/anuraghazra/BugVilla

**Comment by Priyanshu-official** [comment]
@abhisheknaiidu Thank You I will try To make a Similar one

**Comment by Priyanshu-official** [comment]
@abhisheknaiidu Pls Review My PR I think some error was there

**Comment by Priyanshu-official** [comment]
@abhisheknaiidu Please Let me Know The Error on PR

**Comment by abhisheknaiidu** [comment]
@Priyanshu-official WTH have you done,

<img width="1440" alt="Screenshot 2020-10-05 at 10 26 50 PM" src="https://user-images.githubusercontent.com/55599878/95109255-fba04300-0759-11eb-8f60-15fce37f7994.png">

Try to make another PR now.

**Comment by Priyanshu-official** [comment]
@abhisheknaiidu Sorry I got Mail Right Now
I have Checked in my VS code it's Work Fine 
Sorry I Didn't Make it
I am active Night so Late also to check
